services:
  node0:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['0', '7', '1', '6', '8']
  node1:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['1', '3', '5', '2', '4', '0']
  node2:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['2', '1']
  node3:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['3', '1']
  node4:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['4', '9', '1']
  node5:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['5', '1']
  node6:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['6', '0']
  node7:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['7', '0']
  node8:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['8', '0']
  node9:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: ['9', '4']
